pipeline {
    agent any
    
    environment {
        DOCKER_CREDENTIALS_ID = '4b411c55-e9ce-4c5e-afba-1793ea557856'  // Use the actual credential ID you created
        FRONTEND_IMAGE = 'santacodeshere/frontend:latest'
        BACKEND_IMAGE = 'santacodeshere/backend:latest'
    }
    
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/santacodeshere/devop.git'
            }
        }
        
        stage('Build Frontend Docker Image') {
            steps {
                script {
                    dir('frontend') {
                        sh 'docker build -t $FRONTEND_IMAGE .'
                    }
                }
            }
        }
        
        stage('Build Backend Docker Image') {
            steps {
                script {
                    dir('backend') {
                        sh 'docker build -t $BACKEND_IMAGE .'
                    }
                }
            }
        }
        
        stage('Push Docker Images') {
            steps {
                withDockerRegistry([credentialsId: env.DOCKER_CREDENTIALS_ID, url: '']) {
                    script {
                        sh 'docker push $FRONTEND_IMAGE'
                        sh 'docker push $BACKEND_IMAGE'
                    }
                }
            }
        }
    }
}
